[package]
name = "candle-clip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core = "0.3.0"
candle-nn = "0.3.0"
tokenizers = "0.14.1"
tracing = "0.1.40"
